### ISSUE TITLE
[FEATURE]: Bunker/Opslag Loodsen

### ISSUE THREAD

**Issue by timfloors** [Tedeapolis/development#1092]
### Contact Details

MassiveR3T4RD#1741

### Todo

- [x] Item opslag toevoegen
- [x] Drugs functionaliteit kunnen uitschakelen
- [x] Upgrades voor item opslag toevoegen aan loods
- [x] Wapen opslag toevoegen
- [x] Zelf sleutel weg kunnen doen als niet eigenaar

### Beschrijf zo duidelijk mogelijk de feature

Suggestie vanuit Criminele organisatie's. Net besproken in staffoverleg dat dit een prio nodig zou hebben 

![afbeelding](https://user-images.githubusercontent.com/56398140/154860490-8d01d2dd-8109-4ee6-b33d-0f5cf7e020bc.png)

### Wat lost deze feature op?

Voorkomt dat spelers alleen hun huizen en auto's alleen kunnen gebruiken als opslag en dit niet makkelijk kunnen delen met medespelers. Verder dat officiële groepen alleen hun huis kunnen gebruiken als opslag wat een heel groot risico is

**Comment by niekschoemaker** [comment]
Opslag functionaliteit zit erin, zit nu in test fase.
Wapen opslag wordt volgende update.

Wil ook nog even kijken naar systeem dat mensen hun iegen sleutel weg kunnen doen, zodat we die tickets ook niet meer krijgen.

**Comment by Chang-nl** [comment]
Hey @niekschoemaker, hoe staat het hiermee?
