### ISSUE TITLE
KMAR rollen en loonen. Met task list 

### ISSUE THREAD

**Issue by Kobinsky18** [Tedeapolis/development#131]
Nieuwe rangen.

- [x] Luitenant-generaal   blijft staan is de bazen rank alleen nieuwe bevoegdheden er bij.

Bevoegdheden.

- [ ]  Carbinrifle + Mods
- [x]  SMG  + mods
- [x]  pistol
- [x] Taser
- [x]  Flachlite
- [x]  wapenstok
- [x]  Touran 
- [x]  Amarok
- [x]  Audi
- [ ]  Ligtbar
- [x] Motor

- [x] Loon 
In dienst 1150
Uitdienst 500

- [x] Generaal-majoor     moet toegevoegd worden.

Bevoegdheden.
- [x] SMG +mods
- [x] pistol
- [x] Taser
- [x] Flachlite
- [x]  wapenstok
- [x]  Touran 
- [x]  Amarok
- [x]  Audi
- [x] motor

- [x] Loon
In dienst 900
Uitdienst 400

- [x] Kolonel    moet toegevoegd worden.

bevoegdheden.

- [x]  SMG +mods
- [x] pistol
- [x] Taser
- [x] Flachlite
- [x]  wapenstok
- [x]  Touran 
- [x] Amarok
- [x]  Audi
- [x] Motor

- [x] Loon
In dienst 850
Uitdienst 350

- [x] generaal majoor mag vervangen worden naar  Majoor 

bevoegdheden.

- [x] SMG +mods
- [x] pistol
- [x] Taser
- [x] Flachlite
- [x]  wapenstok
- [x]  Touran 
- [x] Amarok
- [x]  Audi
- [x] Motor

- [x] Loon
In dienst 800
Uitdienst 300

- [x] Kolonel mag vervangen worden naar Kapitein 

bevoegdheden.

- [x] SMG + mods
- [x] pistol
- [x] Taser
- [x] Flachlite
- [x]  wapenstok
- [x] Touran 
- [x] Amarok
- [x]  Audi
- [x] Motor

- [x] Loon
In dienst 750
Uitdienst 250

- [x] Kapitein mag vervangen worden naar Luitenant 

bevoegdheden;

- [x] SMG  + mods
- [x] pistol
- [x] Taser
- [x] Flachlite
- [x] wapenstok
- [x]  Touran 
- [x]  Amarok
- [x] -Audi
- [x] Motor

- [x] Loon
In dienst 700
Uitdienst 200

 

- [x]  BSB      Moet helemaal nieuw gemaakt worden.

bevoegdheden.

- [x] Carbinrifle + Mods
- [x]  SMG +mods
- [x] pistol
- [x] Taser
- [x] Flachlite
- [x] wapenstok
- [x] Touran 
- [x] Amarok
- [x] Audi
- [x]  Ligtbar
- [x] Motor

- [x] Loon
In dienst 700
Uitdienst 250

- [x] Opperwachtmeester   mag blijven staan 

bevoegdheden.

- [x]  pistol
- [x]  Taser
- [x]  Flachlite
- [x]  wapenstok
- [x]  Touran 
- [x]  Amarok
- [x]  Motor

- [x] Loon
In dienst 550
Uitdienst 100

- [x] surveillant Wachtmeester   moet vervangen worden naar  Wachtmeester

Bevoegdheden.

- [x]  pistol
- [x]  Taser
- [x]  Flachlite
- [x]  wapenstok
- [x]  Touran 
- [x]  Amarok

- [x] Loon
In dienst 450
Uitdienst 100

- [x] aspirant wachtmeester moet vervangen worden naar marechaussee 1ste klas

bevoegdheden.

- [x]  Taser
- [x]  Pistol
- [x]  Flachlite
- [x]  wapenstok
- [x]  Touran 
- [x]  Amarok

- [x] Loon
In dienst 350
Uitdienst 100
