### ISSUE TITLE
[Bug]: Mazebank kapoet

### ISSUE THREAD

**Issue by sjefoost** [Tedeapolis/development#2533]
### Contact Details

sjeffelicious

### Wat gebeurde er?

Goeiedag, we hebben als groep een mazebank gekocht met 5 extra sleutels. 

Nu is het probleem als volgt, wanneer de sleutelhouders er iets inzetten word het niet geregistreert dus kan niemand anders die voertuigen pakken. ook stapelen de auto's zich op ipv dat ze op de goeie plek komen in de mazebank.
De auto's die je erin zet als sleutelhouder worden nog steeds geregistreerd alsof die je in je eigen garage staan ( dus je betaald alsnog belasting )

Al met al werkt eigenlijk niks, we hebben 1.4m betaald om kosten te besparen en voor de handigheid alleen tot op heden werkt er nog niks.

### Todo

- [x] Als sleutelhouders een voertuig erinzetten word het niet geregistreert dus kan niemand anders de voertuigen pakken
- [x] Voertuigen stapelen op
- [x] Je betaald alsnog belasting over voertuigen als je die er als sleutelhouder inzet

### Wat hoorde er te gebeuren?

wanneer een sleutelhouder een auto erin zet zou die:

Registreert staan in de mazebank zodat andere hem kunnen pakken en niet dat elke spot leeg is
Registreert in eigen garage dat ze in de mazebank staan zodat je geen belasting betaald
De auto's moeten op de goede plek komen te staan in de mazebank want zo stapelen de auto's zich op en dat is niet handig.
Dat iedereen met een sleutel/eigenaar alle auto's kan pakken die erin worden gezet.

### Wat veroorzaakt de bug?

ik weet het oprecht niet, voor clips kun je me dm sturen op discord.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Richtlijnen

- [x] Ik ga akkoord met de issue richtlijnen en heb deze aandachtig gelezen

**Comment by niekschoemaker** [comment]
Even ter verduidelijking, dit gaat puur over als je als "niet eigenaar"/sleutelhouder iets erin zet?

Dus voor de eigenaar zelf werkt alles wel, maar voor sleutelhouders totaal niet als ik het goed begrijp?

**Comment by niekschoemaker** [comment]
Test het na volgende restart nog even, als het goed is zijn de meeste issues zo gefixed.

**Comment by sjefoost** [comment]
Voor eigenaar werkte het wel, alleen die zag ook niet de auto's erin staan die de sleutelhouder erin zet. ik zal het vandaag nog een keer testen en dan laat ik het weten thanks!

**Comment by Tom974** [comment]
Gelukt @sjefoost ?

**Comment by sjefoost** [comment]
nope, wanneer ik als ( sleutelhouder ) de bussen in de mazebank zet van de eigenaar staan deze nu wel geregistreerd in mijn garage alsof ze in de mazebank staan dus dat is gelukt!

Alleen kan ik de auto's niet zien en ook niet eruit pakken.

ook weet ik niet of nu belasting eraf gaat van deze voertuigen of niet. @Tom974 

![image](https://github.com/user-attachments/assets/84d43fe8-ad6f-4c94-9b64-90fe709e1cd3)

![image](https://github.com/user-attachments/assets/3bba0cfc-7876-4d93-971e-6a91273002f8)

**Comment by niekschoemaker** [comment]
Als het goed is is het nu gefixed
