### ISSUE TITLE
Handboeien kunnen kopen 

### ISSUE THREAD

**Issue by takermart** [Tedeapolis/development#37]
handboeien kunnen kopen in plaats van onbeperkt gebruiken . 

handboeien alleen te koop zetten voor criminele organisatie,s. 1k per stuk of desnoods hoger als dit te vaak word misbruikt . 

maar wat als je hem dan de boeien af doet  , heb je dan de handboeien weer terug ? 

# todo
- [x] Maken van item in game
- [x] Aanpassen van job menu voor boeien zodat er een check in zit voor item.
- [x] Item in een winkel beschikbaar

**Comment by Willem-Dekker** [comment]
zit vanaf vandaag in de main server
