### ISSUE TITLE
Snijbrander toevoegen Politie // KMAR (Burgerraad)

### ISSUE THREAD

**Issue by SecretSupplier** [Tedeapolis/development#736]
**Beschrijf zo duidelijk mogelijk de feature**
Graag zien wij het item Snijbrander (politie) in onze opslag. De feature (Breek in voertuig) kan dat uit het f6 menu.

**Wat lost deze feature op?**
Zorgt ervoor dat er daadwerkelijk een item gepakt moet worden om een voertuig open te breken.

**Comment by Willem-Dekker** [comment]
# Todo

- [ ] Toevoegen item aan shop politie.
- [ ] Gedrag snijbrander aan passen dat er een 100% slagingskans is als job politie / kmar is.
- [ ] Optie van snijbrander verwijderen uit F6 menu politie/kmar behouden voor militar.
